# Generated by Django 5.1 on 2024-08-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_washed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Washed on: ')),
                ('type', models.CharField(choices=[('X', 'Exterior'), ('I', 'Interior'), ('W', 'Wheels'), ('F', 'Full Service')], default='X', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Washed',
        ),
    ]
