# Generated by Django 5.1 on 2024-08-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_upgrade_alter_cleaning_options_alter_cleaning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='upgrades',
            field=models.ManyToManyField(to='main_app.upgrade'),
        ),
    ]
